Beta tester-page code cleaned
VilmaNilsson/VIP2021-webpage pull request #92
Opened 2021-04-14 13:48 UTC by LudvigStridsberg

Removed unnecessary html-elements and unnecessary css-rules. Also made it look a bit closer to the provided pdf by, for example, making the video bigger.

2021-04-14 15:31 UTC, VilmaNilsson approved these changes
So much cleaner code than what I did, great!!

2021-04-14 15:33 UTC, VilmaNilsson requested changes
There are some conflicts with this code, otherwise is it good! Much cleaner code than what I did

2021-04-15 11:57 UTC, LudvigStridsberg commented
I see that there are changes requested but I don't get what they are supposed to be. Mind explaining, please?

2021-04-15 12:36 UTC, VilmaNilsson approved these changes

2021-04-15 12:37 UTC, merged